spring:
  application:
    name: dev_error_design
  redis:
    host: 192.168.1.3
  rabbitmq:
    host: 192.168.1.3
    port: 5672
    username: fantasybaby
    password: fantasybaby
server:
  port: 7778
  servlet:
    encoding:
      force: true
      charset: UTF-8

logging:
  config: classpath:logback-spring.xml
